final products = [
  {
    'id': '0',
    'title': 'Adidas Shoes man',
    'price': 120.12,
    'imageUrl': 'assets/images/adidas2.png',
    'company': 'Adidas',
    'sizes': [9, 10, 12],
  },
  {
    'id': '1',
    'title': 'Adidas Shoes',
    'price': 20.12,
    'imageUrl': 'assets/images/adidas1.png',
    'company': 'Adidas',
    'sizes': [9, 10, 12],
  },
  {
    'id': '2',
    'title': ' Nike Sport shoes',
    'price': 44.52,
    'imageUrl': 'assets/images/nike1.png',
    'company': 'Nike',
    'sizes': [9, 10, 11, 12],
  },
  {
    'id': '3',
    'title': ' Nike Sport shoes',
    'price': 44.52,
    'imageUrl': 'assets/images/shoes_3.png',
    'company': 'Nike',
    'sizes': [9, 10, 11, 12],
  },
  {
    'id': '4',
    'title': 'Jordan Shoes',
    'price': 620.69,
    'imageUrl': 'assets/images/shoes_4.png',
    'company': 'Nike',
    'sizes': [8, 9, 10],
  },
  {
    'id': '5',
    'title': 'Cushion shoes',
    'price': 520.69,
    'imageUrl': 'assets/images/shoes_2.png',
    'company': 'Other',
    'sizes': [8, 9, 10],
  },
  {
    'id': '6',
    'title': 'Solomon shoes',
    'price': 320.69,
    'imageUrl': 'assets/images/shoes_1.png',
    'company': 'Other',
    'sizes': [8, 9, 10],
  },
  {
    'id': '7',
    'title': 'Puma shoe',
    'price': 28.95,
    'imageUrl': 'assets/images/puma.png',
    'company': 'Puma',
    'sizes': [8, 9, 10],
  },
];
